@baseUrl = http://localhost:4000
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "Raphael.Marie@gmail.com",
    "password": "secret"
}

###

# @name register
POST {{baseUrl}}/signin
content-type: application/json
Authorization: Bearer

{
  "lastname": "Black",
  "firstname": "Sirius ",
  "email": "sirius@gmail.com",
  "pseudo": "Sisi",
  "password": "secret",
  "description": "Tout droit sorti d'Azkaban",
  "availability": true,
  "tags": [
    1,
    2
  ]
}

###

# @name getUsers
GET {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer 

###

# @name getOneUser
GET {{baseUrl}}/api/users/1
content-type: application/json
Authorization: Bearer 

###

# @name editUser
PUT {{baseUrl}}/api/users/51
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoic2lyaXVzQGdtYWlsLmNvbSIsImlkIjo1MX0sImlhdCI6MTY5MDgyNzUzOCwiZXhwIjoxNjkwODI4NDM4fQ.mKTxXeiPqPdNyqz4C50fTW5gNnl2ARS8cFH_xXJcUxk

{
  "lastname": "Black",
  "firstname": "Sirius ",
  "email": "sirius@gmail.com",
  "pseudo": "Sisi",
  "password": "secret",
  "description": "Tout droit sorti d'Azkaban",
  "availability": true,
  "tags": [
    1,
    3
  ]
}
###

# @name deleteUser
DELETE {{baseUrl}}/api/users/1
content-type: application/json
Authorization: Bearer 

###

# @name getProjects
GET {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer 

###

# @name getOneProject
GET {{baseUrl}}/api/projects/24
content-type: application/json
Authorization: Bearer 

###

# @name createProject
POST {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoic2lyaXVzQGdtYWlsLmNvbSIsImlkIjo1MX0sImlhdCI6MTY5MDgyNzUzOCwiZXhwIjoxNjkwODI4NDM4fQ.mKTxXeiPqPdNyqz4C50fTW5gNnl2ARS8cFH_xXJcUxk

{
  "title": "Harry Potter",
  "description": "Lorem ipsum blabla",
  "availability": true,
  "user_id": 51,
  "tags": [
    1,
    3
  ]
}

###

# @name editProject
PUT {{baseUrl}}/api/projects/25
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoic2lyaXVzQGdtYWlsLmNvbSIsImlkIjo1MX0sImlhdCI6MTY5MDgyNzUzOCwiZXhwIjoxNjkwODI4NDM4fQ.mKTxXeiPqPdNyqz4C50fTW5gNnl2ARS8cFH_xXJcUxk

{
  "title": "Harry Potter 2",
  "description": "Lorem ipsum blabla",
  "availability": false,
  "user_id": 51,
  "tags": [
    1,
    5,
    4
  ]
}

###

# @name deleteProject
DELETE {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

# @name applyToProject
POST {{baseUrl}}/api/projects/3/user/51
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoic2lyaXVzQGdtYWlsLmNvbSIsImlkIjo1MX0sImlhdCI6MTY5MDgyNzUzOCwiZXhwIjoxNjkwODI4NDM4fQ.mKTxXeiPqPdNyqz4C50fTW5gNnl2ARS8cFH_xXJcUxk

###

# @name addUserToProject
PUT {{baseUrl}}/api/projects/3/user/51
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiUmFwaGFlbC5NYXJpZUBnbWFpbC5jb20iLCJpZCI6MjN9LCJpYXQiOjE2OTA4Mjc5ODUsImV4cCI6MTY5MDgyODg4NX0.Y1upsPlkdFT-Q4vvmkk2mZKiCWpXCQN7ZA9VCMk0IV4

###

# @name removeUserToProject
DELETE {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiY2FwdGFpbkBnbWFpbC5jb20iLCJpZCI6Mn0sImlhdCI6MTY4NzQyODEzMiwiZXhwIjoxNjg3NDgyMTMyfQ._XQgPEyfHOAOzBY-uXzYz_gSazIDA1jjbXrcYRL-mCc

###

POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
